export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const TOKEN_CHECKING_REQUEST = "TOKEN_CHECKING_REQUEST";
export const TOKEN_CHECKING_SUCCESS = "TOKEN_CHECKING_SUCCESS";
export const TOKEN_CHECKING_FAILED = "TOKEN_CHECKING_FAILED";


